const OLD_WTF_DETAILS = (() => {
  const WTF_2025_URL = "https://www.afrikaburn.org/wp-content/uploads/2025/04/WTF_OOTB-2025_single-pages.pdf";
  const WTF_2024_URL = "https://www.afrikaburn.org/wp-content/uploads/2024/05/WTF2024-WEB-GOLD.pdf";
  const oldWtfLink = { label: "Old WTF 2025 guide", url: WTF_2025_URL };
  const oldWtf2024Link = { label: "Old WTF 2024 guide", url: WTF_2024_URL };
  const entries = [
    {
      code: "ABB",
      title: "ABnB",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "lounge", "mutant-vehicle"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described ABnB as a dusty safe haven for chilling and connection, with a large lounge, cocktail bar, mini mutant vehicle and soft deep tunes. It framed the camp as a place where people could drop in for an hour, stay for the night, or simply settle in for as long as felt right.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "ASS",
      title: "Alegra Space Station",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "mutant-vehicle", "drinks", "solar-help"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 framed Alegra Space Station as the Tankwa equivalent of the ISS: a camp built around gifting and volunteering, with craft beer, a non-alcoholic cooler, a mutant vehicle cruise and solar-tech help for small solar-system problems.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "BAD",
      title: "BabaDoof",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "bar", "breakfast", "night"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented BabaDoof as a mobile late-night and all-night food-and-drink presence on the Binnekring. Their bar moved to favourite art cars, and their Cereal Killers operation searched for hungry dust dwellers between about 3am and sunrise.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "BEE",
      title: "Bee-Have",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "bees", "stage", "community", "performance"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described BeeHave as a bee-inspired theme camp centred on intelligence, collaboration and pollinators. Its hexagonal BeeHive stage was framed as a place for art, music and performance, with space to relax, reflect and connect.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "BEY",
      title: "Bull's Eye",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "food", "games", "potjie"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 listed Bull's Eye: Jikoni Potjie as a daytime refuel stop for dusty participants, with braai-fired potjie, toasties, drinks, games and a bring-your-own-bowl/cup style dinner-in-the-desert offering.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "BIO",
      title: "Bioskop & Bangaz",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "film", "music", "visual-art"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Bioskop & Bangaz as an interactive collective showcasing local films about African culture and history, fused with live music and visual-art imagery.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "BDS",
      title: "Birthday Suits",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "naturism", "shower", "orange-juice"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 focused on Birthday Suits' Power Shower: a naturist, non-judgemental human car wash built around communal nudity, body respect, a warm soapy wash and cold orange juice.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "BMA",
      title: "Burning Mail",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "postcards", "messages"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Burning Mail as Tankwa Town's post office, where participants could choose postcards, write messages out into the default world, send messages inside Tankwa Town, and add messages to the universe for the Temple burn.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "BUT",
      title: "Buttery Beasts",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "market", "food", "assistance"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Buttery Beasts as a convenience-store-style camp with market days, hot food, cold drinks, buttery beats and playful reptilian cosmetic enhancements, plus a bell for beastly assistance outside market times.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "404",
      title: "Camp 404",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "lounge", "games", "vegan-brunch"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 framed Camp 404 as a 24/7 blanket-fort lounge for the lost and not-found: comfy, safe, snacky and strange, with games, downtempo tunes, lamps to talk to, daily shenanigans and an 11am-ish vegan brunch.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "DEL",
      title: "Camp DelicioZA",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "pancrepes", "campfire", "safe-space"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Camp DelicioZA as a big-hearted community flipping pancrepes in the morning, hosting occasional DJ performances, keeping sunset-to-sunrise campfires burning and offering a welcoming safe space for wandering souls.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "CWN",
      title: "Camp Why Not",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "music", "mutant-vehicles", "sunrise"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 marked Camp Why Not's seventh year with a larger programme: two mutant vehicles, many hours of music, sunrise parties, late-night fries and deliberately timed mysteries.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "COS",
      title: "Cosmic Canvas",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "face-painting", "uv"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented Cosmic Canvas as a UV and metallic face-painting stop with stencil and freestyle options, glow-up checks under UV light, and daytime plus evening painting sessions.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "CUR",
      title: "Curiocity",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "games", "chaos", "interaction"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described CurioCity as a compact burst of energy, chaos, colour and interaction, including a fast, fierce and ridiculous Cup Olympics.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "CYM",
      title: "CYMATICA",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "mad-hatters", "party", "lasers"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 linked CYMATICA to Mad Hatter's Village and its Friday Silver Ball: metallic dress-up, illusion, reflective play, lasers, dancing and cold libations into the early hours.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "DDS",
      title: "Dust Devil Saloon",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "saloon", "bar", "shade", "music"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Dust Devil Saloon Bar as a midday Binnekring watering hole with swinging saloon doors, shade under a Bedouin, icy drinks, tequila, laughter, silky DJ beats and playful bar mischief.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "DIS",
      title: "DisFUNKtion",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "party", "crepes", "lasers"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Camp DisFUNKtion as an international crew bringing BRC energy to AfrikaBurn, with a Tuesday pyjama party at Mad Hatter's Lounge, morning crepes on selected days and an outdoor smoky laser show at night.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "DID",
      title: "Disko Dolce",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "dance", "pasta", "workout"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Disko Dolce as a camp celebrating the good life through dance, connection, a pasta party, disco beats and energising morning workouts.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "DMT",
      title: "DMT",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "music", "acoustic", "electronic"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 identified DMT as a desert music offering built around acoustic tunes and soulful electronic sounds.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "ENO",
      title: "Enos Nookie",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "cosmic", "psy", "pageant"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Enos' Nookie as a cosmic crash-site at the Binnekring edge, with landing lights, glowing sand, a Wednesday psy jol, a Friday beauty pageant and groovy eclectic sessions running deep into the week.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "FCC",
      title: "Fractal Chill",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "coffee", "ethiopian", "cafe", "shade"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Fractal Chill Ethiopian Coffee House as the home of a long-running Ethiopian coffee pot, serving freshly roasted Arabica coffee from a funky Bedouin-style burner cafe and offering a home-away-from-home comfort stop.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "GOW",
      title: "Garden of Weeden",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "arcade", "dancefloor", "lounge"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 split Garden of Weeden into three public spaces: Garden of Play with arcade-style games and mini cinema, Garden of Boogy with an old-school inflatable dancefloor, and Garden of Chill with a relaxed lounge and gifting tree.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TGM",
      title: "The Greasemonkeys",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "mechanical-help", "tools", "teaching", "kids"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described The Greasemonkeys as a tie-dye troupe of mechanically minded monkeys with a passion for spanners. The camp helped with breakdowns, mechanical mishaps and nervous repairs in an each-one-teach-one style, with a mini-monkeys tinkering area for toddlers and storytime most days.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "HOB",
      title: "The House Of Boho",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "creativity", "music", "food", "morning"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 linked House of Boho with lively 4:20 creative sessions, music, food and camaraderie. The blurb described morning African-style vetkoeks, gin-and-tonic energy and a camp atmosphere built around artists gathering and celebrating creativity.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "HSP",
      title: "HeartSpace",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "sober", "connection", "workshops"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described HeartSpace as a sober, heart-centred space for deep connection, conscious touch and embodied expression, with morning yoga, breathwork, afternoon workshops and more intimate evening events.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "HYD",
      title: "Hydration Station",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "water", "hydration"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented Hydration Station as a water-gifting crew on a mission to keep people hydrated and happy, with filtered sealed drinking water brought by the camp's water warriors for those in need.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "KAG",
      title: "Kaggen meets Rainbow dancers",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "rainbow", "indigenous", "community"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 listed this as Rainbow, a camp centred on shared humanity, respect, love for all beings and a tribute to indigenous wisdom across tribes.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "KRE",
      title: "KREME",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "sweets", "beats", "yoga"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described KREME as a colourful interactive camp of sweets, beats, lights and imagination, with daytime techno yoga, breathwork, gluhwein, smores and a broadly welcoming mood.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "LCT",
      title: "La Casa Timeless",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "bar", "music", "workshops"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 framed La Casa Timeless as a myth-and-reality blur with cocktails, dim sum, DJ sets, live music, sonic sand meditation, transformative discussions and mask-making before a Friday masquerade.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "LOL",
      title: "Lands of Love",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "land", "care", "camping"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 marked Lands of Love as a camp devoted to the many ways people love the land. The extractable guide text is partial, but the listing clearly places its public identity around land care, morning/daytime presence and a land-loving camp offering.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "LPP",
      title: "Le Petit Paris",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "sunset", "champagne", "lounge"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Le Petit Paris as a sunset champagne and DJ-set stop, with sunrise acoustic performances, fresh bubbly and a cosy shaded lounge for connection in the desert.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "LUM",
      title: "Luminosity Lounge",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "lounge", "braai", "quiet"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Luminosity Lounge as a daytime food-and-music lounge that became a nighttime place to rest ears, reflect and talk under the stars just outside the main music envelope.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "MAL",
      title: "MAHALA",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "breathwork", "sound", "tea"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented Mahala as a sacred journey space for inner exploration, with breathwork, tantra, sound journeys, storytelling, daily sessions, midnight rituals, a fire circle and tea bar.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "MIM",
      title: "Mimosa Avenue",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "mimosas", "music"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Mimosa Avenue as a midday-to-afternoon stop for cold mimosas, curated music, drinks and tunes in the heat of the desert day.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "PAN",
      title: "The Pancake People",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "pancakes", "show", "social"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described The Pancake People as a long-running pancake show that drew burners across the Binnekring into batter-covered mayhem, music, laughter and spontaneous social connection.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "PAP",
      title: "Pamoja Project",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "afrohouse", "juice", "global"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 emphasised Pamoja's African music focus, with afternoon Afrohouse, Afrobeats and Amapiano parties, plus morning orange juice, workshops and a globally mixed camp community.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "PFP",
      title: "Pedals for Peace",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "bikes", "outreach"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Pedals for Peace as a bike-rental camp where funds raised at AfrikaBurn support bikes gifted back to identified projects in the default world.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "PIC",
      title: "Pickles & Prickles",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "dance", "mural", "workshops"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented Pickles & Prickles as an expressive dance and art camp with afternoon parties, bubbly beverages, pickled pleasures, a collaborative mural and a chalkboard of workshops and daily offerings.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "PCM",
      title: "Professor Cuchulain's Magic Elixirs and Apothecary",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "elixirs", "performance"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Professor Cuchulain and assistants as a theatrical snake-oil sales team offering samples of magic elixirs from an apothecary and travelling soapbox show.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SAC",
      title: "Sacred Garden",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "fans", "hot-drinks", "night"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Sacred Garden as an international creative community gifting designed fans and a mobile bar serving healthy natural hot drinks across the desert nights.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SEX",
      title: "Sexico City",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "music", "mexican", "party"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented Sexico City as a high-vibe Mexican and international crew bringing music, food, drink and a welcome party in Mad Hatter's Village.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SMS",
      title: "Smokescreen",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "theatre", "movies", "music"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Smokescreen as Tankwa's original theatre and party venue, with movies, art, music, costumes, personality, a homemade style and a daily blackboard for shifting event times.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SCB",
      title: "Space Cowboys",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "dancefloor", "music", "night"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Space Cowboys as a long-running galactic dancefloor camp and intergalactic oasis powered by a collective of sonic engineers, musicians and cosmic dreamers.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SUN",
      title: "Sunrisers",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "coffee", "morning", "collaboration"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Sunrisers as a morning coffee gift from 7am, followed by a collaborative space for yoga, photography, talks or other art and artistry until late morning.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SSO",
      title: "Sunset Oasis",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "rest", "spa", "showers"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 noted Sunset Oasis as a long-running camp known for a quieter resting atmosphere, soft music, reflective seating, spa time and showers on selected days.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "STR",
      title: "Super Tramps",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "trampoline", "play", "lounge"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented Super Tramps as a gravity-defying play camp where people could bounce, flip, lounge and hang out under the desert sky.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SLC",
      title: "The Sweet Love Cinema",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "cinema", "movies", "night"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Sweet Love Cinema as a long-running cinema camp playing kid-friendly films from sunset into the early morning.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TAS",
      title: "The ArtSluts",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "build", "artists", "breakfast"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 cast The ArtSluts as build-week helpers for AfrikaBurn artists: a practical crew with tools and skills, ready to assist creative tasks and host Builders' Breakfast.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TBA",
      title: "The Burning Arms",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "pub", "beer", "quizzes"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described The Burning Arms as a traditional English pub in the dust, serving beer and hosting activities such as karaoke and pub quizzes.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "CAT",
      title: "Home of the Psychic Cat",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "tea", "video", "croquet"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 connected Home of the Psychic Cat with the Airspace crew and described nightly art-video shows, a costumed tea-and-biscuits event, wine-and-croquet, FleaBurn and a haka dance.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TMB",
      title: "The MemberBerries",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "reflection", "inclusion", "chill"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described The MemberBerries as a small group of dispersed berries who found one another in the immediacy of the default and experimental world, offering space for relaxation, reflection, self-expression, inclusion and chilling out.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TLD",
      title: "The Lion's Den",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "mutant-vehicles", "music", "produce"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described The Lion's Den as a home for seasoned South African burners, with three mutant vehicles, daytime ambient music, refreshing local produce, pop-ups and bigger nighttime parties.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "RRH",
      title: "Ra Ra",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "sunset", "lounge", "dance"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 listed The Ra Ra Hive as a sunset-focused lounge and dance space inspired by Ra, with sundowners, soft dancefloor energy and daily late-afternoon opening.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "VAG",
      title: "Vagabonds",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "wellness", "massage", "sky-lounge"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Vagabonds as a wellness and relaxation camp with daily massages, a lounge for connection, a sky lounge over the Binnekring and workshops for mental and physical wellbeing.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TWS",
      title: "The Wet Spot",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "shower", "morning"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described The Wet Spot as a warm morning shower gift in the desert, with four shower cubicles, heated pumped water and a requirement that participants bring their own water.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TTS",
      title: "Time to Shine",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "stage", "performance"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 presented Time to Shine as a small stage for people to try performing, exhibit a desired talent and be seen by the rest of the camp.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "TUL",
      title: "Tulpa",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "creativity", "workshops", "music"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Tulpa as a playground of creativity, music and connection inspired by thoughtforms brought to life, with workshops, day parties, massage and groovy rhythms.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "SPS",
      title: "The Steampunk Saloon",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "saloon", "burlesque", "music"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 described Steampunk Saloon as a feminine desert oasis for dusty voyeurs, with workshops by day, lyric-heavy music, late boogies and burlesque shows around 6pm on Thursday, Friday and Saturday.",
      }],
      links: [oldWtfLink],
    },
    {
      code: "WAJ",
      title: "Wild & Juicy",
      type: "Historical WTF",
      tags: ["old-wtf", "2025", "juice", "mobile", "vitamins"],
      oldWtf: [{
        year: 2025,
        summary: "Old WTF 2025 listed Wild & Juicy as a mobile vitamin-and-juice gift, asking participants to look out for a small blue trailer on the Binnekring serving fresh juice with dusty love.",
      }],
      links: [oldWtfLink],
    },
  ];

  return {
    sourceTag: "old-wtf",
    sourceLabel: "Old WTF",
    sourceUrl: WTF_2025_URL,
    sourceFetchedAt: "2026-04-20",
    sources: [
      { year: 2025, label: "Old WTF 2025 guide", url: WTF_2025_URL },
      { year: 2024, label: "Old WTF 2024 guide", url: "https://www.afrikaburn.org/wp-content/uploads/2024/05/WTF2024-WEB-GOLD.pdf" },
      { year: 2023, label: "Old WTF 2023 guide", url: "https://www.afrikaburn.org/wp-content/uploads/2023/04/WTF2023-FA-web2.pdf" },
    ],
    entries,
    byCode: Object.fromEntries(entries.map((entry) => [entry.code, entry])),
  };
})();
